
language: erlang

matrix:

  include:
    - os: linux
      dist: focal
      otp_release: 24.0.2

    - os: linux
      dist: focal
      otp_release: 23.1.2

    - os: linux
      dist: bionic
      otp_release: 22.3

    - os: osx
      osx_image: xcode12.2
      language: generic

before_script:

- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ $TRAVIS_OS_NAME == osx ]]; then brew install erlang || true; fi

- curl https://s3.amazonaws.com/rebar3/rebar3 --output rebar3 && chmod +x rebar3

script:
    - ./rebar3 compile

after_success:
    - ./rebar3 ct
