
language: erlang

matrix:

  include:
    - os: linux
      dist: bionic
      otp_release: 23.3.1

    - os: linux
      dist: focal
      otp_release: 24.3.1

    - os: linux
      dist: focal
      otp_release: 25.0

    - os: osx
      osx_image: xcode12.4
      language: generic
      env:
        - HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=true
        - HOMEBREW_NO_INSTALL_UPGRADE=true
        - HOMEBREW_NO_INSTALL_CLEANUP=true
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew

before_script:

- if [[ $TRAVIS_OS_NAME == osx ]]; then brew install erlang || true; fi

- curl https://s3.amazonaws.com/rebar3/rebar3 --output rebar3 && chmod +x rebar3

script:
    - ./rebar3 compile

after_success:
    - ./rebar3 eunit
